# -*- coding: utf-8 -*-
"""Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QprKXmXFo132jtLhIyhK8S3QCO5j6fP

Task 1: User Login Check
"""

stored_username = "admin"
stored_password = "1234"

# Given input
username = "admin"
password = "1234"

# Login validation
if username == stored_username and password == stored_password:
    print("Login Successful")
else:
    print("Invalid Credentials")

"""Task 2: Pass / Fail Analyzer"""

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print("Total Students:", len(marks))
print("Total Pass:", pass_count)
print("Total Fail:", fail_count)

"""Task 3: Simple Data Cleaner"""

names = [" Alice ", "bob", " CHARLIE "]

cleaned_names = []

for name in names:
    cleaned_name = name.strip().lower()  # Remove spaces and convert to lowercase
    cleaned_names.append(cleaned_name)

print("Cleaned Names:", cleaned_names)

"""Task 4: Message Length Analyzer"""

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:
    length = len(message)
    print(f"Message: '{message}' | Length: {length}")

    if length > 10:
        print("⚠️ This message is longer than 10 characters.")

""" Task 5: Error Message Detector"""

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = logs.count("ERROR")

print("Total ERROR messages:", error_count)

